name: Integration Tests

on: [pull_request]

jobs:
  integration-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Backend steps
      - name: Install Npm Packages for Backend
        run: npm install
        working-directory: server

      - name: Run integration tests
        run: npm test
        working-directory: server
